# Generated by Django 5.0.6 on 2024-05-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_filme_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='primeiro_nome',
            new_name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sobrenome',
        ),
    ]
