# Generated by Django 5.0.6 on 2024-05-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_primeiro_nome_usuario_nome_completo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome_completo',
            new_name='senha',
        ),
        migrations.AddField(
            model_name='filme',
            name='capa_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='url_filme',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='capa_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='url_serie',
            field=models.URLField(blank=True),
        ),
    ]
